# Generated by Django 5.1.1 on 2024-09-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barchart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="barchart",
            name="label",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="candlestickchart",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="candlestickchart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="linechart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="linechart",
            name="label",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="piechart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="piechart",
            name="label",
            field=models.CharField(max_length=255),
        ),
    ]
